Improve UX

diff --git a/scripts/run b/scripts/run
--- a/scripts/run
+++ b/scripts/run
@@ -1,14 +1,17 @@
 #!/usr/bin/env bash
 set -e
 
-echo "Usage: ./run PATH_TO_CONFIG [--public]"
-echo "Options:"
-echo "  --public    Pull from public docker registry (master tag only)"
+if [[ "$#" -lt 1 || "$#" -gt 2 ]]; then
+    echo "Usage: ./run PATH_TO_CONFIG [--public]"
+    echo "Options:"
+    echo "  --public    Pull from public docker registry (master tag only)"
+    exit 1
+fi
 
 CONFIG_PATH=$1
 
 if [ ! -f $CONFIG_PATH ]; then
-    echo "Config file not found."
+    echo "Config file not found at $CONFIG_PATH"
     echo "Please create a config file in the same format as the config-example.json file in this repo."
     exit -1;
 fi
